#ifndef SCHC_OVER_SIGFOX_C_SCHC_H
#define SCHC_OVER_SIGFOX_C_SCHC_H

#endif //SCHC_OVER_SIGFOX_C_SCHC_H

#define UPLINK_MTU_BYTES 12
#define UPLINK_MTU_BITS (UPLINK_MTU_BYTES * 8)
#define DOWNLINK_MTU_BYTES 8
#define DOWNLINK_MTU_BITS (DOWNLINK_MTU_BYTES * 8)

#define SCHC_SENDER_ABORTED 1
#define SCHC_RECEIVER_ABORTED 2
#define SCHC_COMPLETED 3

#define MAX_NB_RULE_IDS 17

extern char FR_MODE[];
extern int RETRANSMISSION_TIMEOUT;
extern int SIGFOX_DL_TIMEOUT;
extern int INACTIVITY_TIMEOUT;
extern int MAX_ACK_REQUESTS;
extern const int L2_WORD_SIZE;
extern int DELAY_BETWEEN_FRAGMENTS;

// Sender config
extern int DISABLE_MAX_ACK_REQUESTS;
extern int UPLINK_LOSS_RATE;
extern int DOWNLINK_LOSS_RATE;

// Receiver config
extern int RESET_DATA_AFTER_REASSEMBLY;
extern int CHECK_FOR_CALLBACK_RETRIES;
extern int DISABLE_INACTIVITY_TIMEOUT;
extern char RECEIVER_URL[];